// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://belvjbowviufapxotyqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbHZqYm93dml1ZmFweG90eXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDY5MzAsImV4cCI6MjA2NDE4MjkzMH0.IL0IDtu_GqVPzKYh236lbJjayU0ocxh-lG_P8cGVzis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);